"""Build and run a FastAPI mock server from parsed routes."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from .generator import MockDataGenerator
from .parser import OpenAPIParser, RouteDefinition


def convert_openapi_path(path: str) -> str:
    """Convert OpenAPI path params {id} to FastAPI format {id}."""
    # FastAPI uses the same {param} syntax as OpenAPI, so no conversion needed
    return path


def create_mock_app(
    spec: dict[str, Any],
    seed: int | None = 42,
    title: str = "API Mocker",
) -> FastAPI:
    """Create a FastAPI app that serves mock responses based on an OpenAPI spec.

    Args:
        spec: An OpenAPI 3.x specification dictionary.
        seed: Random seed for reproducible mock data. None for random.
        title: Title for the FastAPI app.

    Returns:
        A configured FastAPI application.
    """
    parser = OpenAPIParser.from_dict(spec)
    routes = parser.parse()
    generator = MockDataGenerator(seed=seed)

    info = spec.get("info", {})
    app = FastAPI(
        title=info.get("title", title),
        description=info.get("description", "Mock API generated by api-mocker"),
        version=info.get("version", "0.1.0"),
    )

    for route in routes:
        _register_route(app, route, generator)

    # Add a metadata endpoint
    @app.get("/__mock__/routes")
    async def list_routes() -> list[dict[str, Any]]:
        """List all registered mock routes."""
        return [
            {
                "path": r.path,
                "method": r.method,
                "operation_id": r.operation_id,
                "summary": r.summary,
                "status_code": r.status_code,
            }
            for r in routes
        ]

    return app


def _register_route(
    app: FastAPI,
    route: RouteDefinition,
    generator: MockDataGenerator,
) -> None:
    """Register a single mock route on the FastAPI app."""
    fastapi_path = convert_openapi_path(route.path)
    mock_data = generator.generate(route.response_schema)
    status_code = route.status_code

    async def handler(request: Request, _data: Any = mock_data, _code: int = status_code) -> JSONResponse:
        return JSONResponse(content=_data, status_code=_code)

    method_map = {
        "GET": app.get,
        "POST": app.post,
        "PUT": app.put,
        "PATCH": app.patch,
        "DELETE": app.delete,
        "HEAD": app.head,
        "OPTIONS": app.options,
    }

    decorator = method_map.get(route.method)
    if decorator is None:
        return

    decorator(
        fastapi_path,
        status_code=status_code,
        summary=route.summary,
        operation_id=route.operation_id,
    )(handler)


def create_app_from_file(
    spec_path: str | Path,
    seed: int | None = 42,
) -> FastAPI:
    """Create a mock app from a spec file path.

    Args:
        spec_path: Path to an OpenAPI 3.x JSON spec file.
        seed: Random seed for reproducible mock data.

    Returns:
        A configured FastAPI application.
    """
    path = Path(spec_path)
    with open(path) as f:
        spec = json.load(f)
    return create_mock_app(spec, seed=seed)
